import { describe, expect, it } from "vitest";

import { calculateScore } from "./dispatch.service";

describe("dispatch.service", () => {
  it("retourne 0 si le brancardier est indisponible", () => {
    const score = calculateScore(
      {
        id: "p1",
        userId: "u1",
        status: "busy",
        skills: ["BRANCARD", "URG"],
        completedMissionsToday: 2,
        rating: 4,
        user: { firstName: "A", lastName: "B", username: "ab" },
      },
      {
        id: "t1",
        patientId: "x",
        patientName: "Patient",
        origin: "Urgences",
        destination: "Bloc",
        priority: 1,
        mode: "Brancard",
        status: "pending",
        requesterId: "u2",
        needsO2: false,
        needsPerfusion: false,
        isolation: false,
        patientAgitated: false,
        patientMonitoring: false,
        needsTwoPorters: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        scheduledTime: null,
        completedAt: null,
        transportType: "PATIENT",
        transportSubtype: "TP-BRANC",
        porterId: null,
        notes: null,
        patientWeight: null,
        equipmentRecipientPatientId: null,
        equipmentRecipientPatientName: null,
        equipmentSize: null,
        equipmentReturnService: null,
        equipmentDelivered: null,
        equipmentLabelReturned: null,
        laboratoryName: null,
        specimenTypes: [],
        notesForReception: null,
        helpRequested: false,
        helpPorterId: null,
        helpStatus: null,
        helpRequestedAt: null,
        isArchived: false,
        archivedAt: null,
        reservationLockedBy: null,
        reservationLockedAt: null,
        activationMinutesBefore: null,
        isVisibleToPorters: true,
        patientContentious: false,
        patientConfused: false,
        patientOver120kg: false,
        patientBariatric: false,
        patientPsychiatry: false,
        patientDialysis: false,
        patientIcu: false,
        otherPrecautions: null,
        patientFirstName: null,
        patientLastName: null,
        patientDob: null,
        patientSex: null,
        patientIpp: null,
        motif: null,
      },
    );

    expect(score).toBe(0);
  });
});