pub mod api_compat;
pub mod auth;
pub mod gdpr;
pub mod health;
pub mod notifications;
pub mod patients;
pub mod porters;
pub mod priority_rules;
pub mod referentials;
pub mod services;
pub mod tickets;
pub mod users;

pub use api_compat::configure as configure_api_compat;
pub use auth::configure as configure_auth;
pub use gdpr::configure as configure_gdpr;
pub use health::configure as configure_health;
pub use notifications::configure as configure_notifications;
pub use patients::configure as configure_patients;
pub use porters::configure as configure_porters;
pub use priority_rules::configure as configure_priority_rules;
pub use referentials::configure as configure_referentials;
pub use services::configure as configure_services;
pub use tickets::configure as configure_tickets;
pub use users::configure as configure_users;
